### ISSUE TITLE
Error NaN

### ISSUE THREAD

**Issue by web-ap** [belotte55/colissimo#1]
Thanks for your package. I tried to use it in a nodejs app, and I the following error in console : 
"Error: soap:Client: Unmarshalling Error: Not a number: NaN" and it doesn't display the tracking_number and label. 
Note that the request/credentials work with postman.

How do you receive and display the results ? 

Thanks

**Comment by belotte55** [comment]
Hi !

Can you log the parameters you pass to the function to generate the label ?
I think you pass a NaN value, so you have to search where is it generated.
You can share me screenshot or code if you want I help you ;)
The function do not display anything, but returns an object containing the
label link and the tracking number.

Frank.

**Comment by web-ap** [comment]
Hi,

Thanks for your quick reply. Actually, I just copy/pasted your example and replaced contract_number and password details. 
And I've got the full response in console log, with this body : 
`'<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><soap:Fault><faultcode>soap:Client</faultcode><faultstring>Unmarshalling Error: Not a number: NaN </faultstring></soap:Fault></soap:Body></soap:Envelope>'`

**Comment by belotte55** [comment]
I have no computer to try it now. I will try to see tomorrow.
Ask me again if I forgot ;)
